[package]
name = "hello_world"
version = "0.1.0"
authors = ["Max Fang <protonmail.com@maxfa.ng>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "hello_world"
path = "main.rs"
